import os
import pandas as pd
import numpy as np
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from pptx import Presentation
from pptx.util import Inches, Pt
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf_report(df_summary, insights, output_path, title="Dataset Analysis Executive Report"):
    """
    Generates a structured, professional PDF report.
    df_summary: descriptive statistics DataFrame to display as a table.
    insights: dict with keys 'findings', 'recommendations', 'action_items'.
    """
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        doc = SimpleDocTemplate(output_path, pagesize=letter,
                                rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=colors.HexColor('#1A2530'),
            spaceAfter=15
        )
        h2_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=16,
            leading=20,
            textColor=colors.HexColor('#2C3E50'),
            spaceBefore=15,
            spaceAfter=10,
            keepWithNext=True
        )
        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#333333'),
            spaceAfter=8
        )
        bullet_style = ParagraphStyle(
            'Bullet',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#333333'),
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=6
        )
        
        # Title
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 10))
        story.append(Paragraph("Automated report generated by Dataset Analysis Platform.", body_style))
        story.append(Spacer(1, 15))
        
        # Section: Executive Summary
        story.append(Paragraph("1. Executive Summary", h2_style))
        story.append(Paragraph("This report provides an overview of the dataset statistical properties, key correlations, outlier behavior, and automatically generated analytical insights.", body_style))
        story.append(Spacer(1, 10))
        
        # Section: Key Findings
        story.append(Paragraph("2. Key Findings", h2_style))
        for finding in insights.get("findings", []):
            story.append(Paragraph(f"&bull; {finding}", bullet_style))
        story.append(Spacer(1, 10))
        
        # Section: Recommendations & Action Items
        story.append(Paragraph("3. Recommendations & Action Items", h2_style))
        story.append(Paragraph("<b>Recommendations:</b>", body_style))
        for rec in insights.get("recommendations", []):
            story.append(Paragraph(f"&bull; {rec}", bullet_style))
            
        story.append(Spacer(1, 5))
        story.append(Paragraph("<b>Suggested Action Items:</b>", body_style))
        for item in insights.get("action_items", []):
            story.append(Paragraph(f"&bull; {item}", bullet_style))
            
        story.append(PageBreak())
        
        # Section: Descriptive Statistics Table
        story.append(Paragraph("4. Descriptive Statistics Table", h2_style))
        
        # Convert df_summary to list of lists for ReportLab Table
        # Limit columns or rows if too wide/long
        df_display = df_summary.reset_index()
        # Clean float representations
        df_display = df_display.round(3)
        
        # Limit rows/columns to fit letter page width
        cols_to_keep = ['index', 'Count', 'Mean', 'Median', 'Std Dev', 'Min', 'Max', 'Missing Values']
        cols_present = [c for c in cols_to_keep if c in df_display.columns]
        df_display = df_display[cols_present]
        
        table_data = [df_display.columns.tolist()]
        for _, row in df_display.iterrows():
            table_data.append(row.tolist())
            
        # Format table
        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2C3E50')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 9),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#F4F6F7')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,1), (-1,-1), 8),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        
        story.append(t)
        
        doc.build(story)
        return True
    except Exception as e:
        raise IOError(f"Failed to generate PDF report: {str(e)}")

def generate_excel_report(df_raw, df_cleaned, df_stats, output_path):
    """
    Generates a formatted multi-sheet Excel spreadsheet.
    """
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        wb = Workbook()
        
        # Sheet 1: Raw Data (first sheet created by default)
        ws_raw = wb.active
        ws_raw.title = "Raw Data"
        
        # Sheet 2: Cleaned Data
        ws_cleaned = wb.create_sheet(title="Cleaned Data")
        
        # Sheet 3: Statistics
        ws_stats = wb.create_sheet(title="Descriptive Statistics")
        
        # Populate Sheets helper
        def populate_sheet(ws, data_df):
            # Header Font and styling
            header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
            header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
            align_center = Alignment(horizontal="center", vertical="center")
            
            # Write Header
            headers = data_df.columns.tolist()
            if isinstance(data_df.index, pd.Index) and data_df.index.name:
                headers = [data_df.index.name] + headers
            elif ws.title == "Descriptive Statistics":
                headers = ["Feature"] + headers
                
            ws.append(headers)
            
            # Style header row
            for col_num in range(1, len(headers) + 1):
                cell = ws.cell(row=1, column=col_num)
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = align_center
                
            # Write data rows
            for r_idx, row in data_df.iterrows():
                row_vals = []
                if ws.title == "Descriptive Statistics" or (isinstance(data_df.index, pd.Index) and data_df.index.name):
                    row_vals.append(str(r_idx))
                for val in row.values:
                    # Clean up numpy types for openpyxl compatibility
                    if isinstance(val, (np.integer, np.int64)):
                        row_vals.append(int(val))
                    elif isinstance(val, (np.floating, np.float64)):
                        row_vals.append(float(val) if not np.isnan(val) else None)
                    elif pd.isna(val):
                        row_vals.append(None)
                    else:
                        row_vals.append(val)
                ws.append(row_vals)
                
            # Auto-fit columns
            for col in ws.columns:
                max_len = 0
                col_letter = col[0].column_letter
                for cell in col:
                    if cell.value is not None:
                        max_len = max(max_len, len(str(cell.value)))
                ws.column_dimensions[col_letter].width = max(max_len + 3, 10)
                
        # Populate each sheet (limit row count to 5000 to keep report generation snappy)
        populate_sheet(ws_raw, df_raw.head(5000))
        populate_sheet(ws_cleaned, df_cleaned.head(5000))
        populate_sheet(ws_stats, df_stats)
        
        wb.save(output_path)
        return True
    except Exception as e:
        raise IOError(f"Failed to generate Excel report: {str(e)}")

def generate_ppt_report(insights, output_path, title="Dataset Analysis Findings"):
    """
    Generates a clean PowerPoint slide deck.
    """
    from pptx.dml.color import RGBColor
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        prs = Presentation()
        
        # Theme colors
        navy = RGBColor(26, 37, 48)
        charcoal = RGBColor(51, 51, 51)
        
        # 1. Slide: Title
        slide_layout = prs.slide_layouts[0] # Title slide
        slide = prs.slides.add_slide(slide_layout)
        title_box = slide.shapes.title
        subtitle_box = slide.placeholders[1]
        
        title_box.text = title
        subtitle_box.text = "Executive Summary and Business Recommendations\nAutomated Report"
        
        # Apply styling to title
        title_para = title_box.text_frame.paragraphs[0]
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(26, 37, 48)
        
        # 2. Slide: Executive Summary / Findings
        slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        
        # Set Title
        title_shape = slide.shapes.title
        title_shape.text = "Key Findings"
        title_shape.text_frame.paragraphs[0].font.bold = True
        title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(26, 37, 48)
        
        # Add Bullet points
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.clear()
        
        findings = insights.get("findings", [])[:6] # Top 6 findings
        for idx, finding in enumerate(findings):
            p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
            p.text = finding
            p.level = 0
            p.font.size = Pt(16)
            p.font.color.rgb = RGBColor(51, 51, 51)
            
        # 3. Slide: Recommendations & Action Items
        slide = prs.slides.add_slide(slide_layout)
        
        title_shape = slide.shapes.title
        title_shape.text = "Recommendations & Action Items"
        title_shape.text_frame.paragraphs[0].font.bold = True
        title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(26, 37, 48)
        
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.clear()
        
        p = tf.paragraphs[0]
        p.text = "Business Recommendations:"
        p.level = 0
        p.font.bold = True
        p.font.size = Pt(18)
        
        for rec in insights.get("recommendations", [])[:3]:
            p_rec = tf.add_paragraph()
            p_rec.text = rec
            p_rec.level = 1
            p_rec.font.size = Pt(14)
            p_rec.font.color.rgb = RGBColor(51, 51, 51)
            
        p_act_title = tf.add_paragraph()
        p_act_title.text = "Operational Action Items:"
        p_act_title.level = 0
        p_act_title.font.bold = True
        p_act_title.font.size = Pt(18)
        p_act_title.space_before = Pt(10)
        
        for item in insights.get("action_items", [])[:3]:
            p_item = tf.add_paragraph()
            p_item.text = item
            p_item.level = 1
            p_item.font.size = Pt(14)
            p_item.font.color.rgb = RGBColor(51, 51, 51)
            
        prs.save(output_path)
        return True
    except Exception as e:
        raise IOError(f"Failed to generate PPT report: {str(e)}")
